#!/bin/bash

. env.sh

clubhouse_id="$1"
user="mika"
token="$CLUBHOUSE_API_TOKEN"

if [ -z "$clubhouse_id" ]; then
  echo "Missing Clubhouse ID (e.g. 1234)"
  exit 1
fi

re='^[0-9]+$'
if ! [[ $clubhouse_id =~ $re ]] ; then
   echo "error: Clubhouse ID not a number" >&2
   exit 1
fi

story=`curl --silent -X GET -H "Content-Type: application/json" -L "https://api.clubhouse.io/api/v2/stories/$clubhouse_id?token=$CLUBHOUSE_API_TOKEN"`

re=',"name":"([^"]+)"'
if [[ $story =~ $re ]]; then
  name="${BASH_REMATCH[1]}"
else
  echo "Could not extract name, exiting..."
  echo
  echo $story
  exit 2
fi

convert=`echo $name | sed 's/[^a-zA-Z]/-/g'`
branch="mika/ch$clubhouse_id/${convert,,}"

if [ `git branch | egrep "^[[:space:]]+${branch}$"` ]; then
  git checkout $branch
else
  current_branch=$(git rev-parse --abbrev-ref HEAD)
  if [[ "$current_branch" != "master" ]]; then
    echo "Refusing to create new branch from $current_branch. Check out master branch and try again."
    exit 3
  fi

  git checkout -b $branch
  git push -u
fi

curl --silent -X PUT -H "Content-Type: application/json" -d '{ "workflow_state_id": 500000019 }' -L "https://api.clubhouse.io/api/v2/stories/$clubhouse_id?token=$token" > /dev/null
