#!/bin/bash

help_text="
Usage:
club [-n] [--notoggl] <STORY_ID>

-n, --notoggl
  Disable toggl time entries.

EXAMPLES:
club 1234
club -n 1234
"

toggl=true

while [[ $# -gt 0 ]]
do
  case $1 in
    -n|--notoggl)
      toggl=false
      shift 
      ;;
    help)
      echo "$help_text"
      exit 0
      ;;
    *)
      story_id=$1
      shift 
      ;;
  esac
done


if [[ `git status --porcelain` ]]; then 
  echo "You have unsaved changes. Please commit or stash them before running this command." 
  exit 5
fi

user="$tools_clubhouse_user"
token="$tools_clubhouse_api_token"

if [ -z "$story_id" ]; then
  git checkout master
  exit 0
fi

re='^[0-9]+$'
if ! [[ $story_id =~ $re ]] ; then
   echo "error: Clubhouse ID not a number" >&2
   exit 1
fi

story=`curl --silent -X GET -H "Content-Type: application/json" -L "https://api.clubhouse.io/api/v2/stories/$story_id?token=$token"`

story_name=`echo $story | jq -r '.name'`
if [ "$story_name" = 'null' ]; then
  echo "Could not extract name, exiting..."
  echo
  echo $story
  exit 2
fi

converted_story_name=`echo $story_name | sed 's/[^a-zA-Z]/-/g'`

if [ "$toggl" = true ]; then
  toggl "$story_id/${converted_story_name,,}"
  echo
fi

existing_branch=`echo $story | jq -r '.branches[0].name'`

if [ "$existing_branch" = 'null' ]; then
  branch_name=`echo "$user/ch$story_id/${converted_story_name,,}" | cut -b 1-60`

  git checkout master && git pull && git checkout -b $branch_name && git push -u

  if [ $? -eq 0 ]; then
    echo Moving story to \"In Progress\"
    curl --silent -X PUT -H "Content-Type: application/json" -d '{ "workflow_state_id": 500000019 }' -L "https://api.clubhouse.io/api/v2/stories/$story_id?token=$token" > /dev/null
    echo All done.
  else
    echo Something went wrong, not moving Clubhouse issue
  fi
else
  git fetch
  git checkout $existing_branch

  if [ $? -ne 0 ]; then
    git checkout master && git pull && git checkout -b $user/ch$story_id/${converted_story_name,,} && git push -u
  fi
fi
