#!/bin/bash

help_text="
Usage:
club [-t] [--toggl] <STORY_ID>

-t, --toggl
  Start a Toggl time entry for the provided story id

EXAMPLES:
club 1234
club -t 1234
"

while [[ $# -gt 0 ]]
do
  case $1 in
    -t|--toggl)
      toggl=true
      shift 
      ;;
    help)
      echo "$help_text"
      exit 0
      ;;
    *)    
      story_id=$1
      shift 
      ;;
  esac
done


if [[ `git status --porcelain` ]]; then 
  echo "You have unsaved changes. Please commit or stash them before running this command." 
  exit 5
fi

user="$tools_clubhouse_user"
token="$tools_clubhouse_api_token"

if [ -z "$story_id" ]; then
  git checkout master
  exit 0
fi

re='^[0-9]+$'
if ! [[ $story_id =~ $re ]] ; then
   echo "error: Clubhouse ID not a number" >&2
   exit 1
fi

story=`curl --silent -X GET -H "Content-Type: application/json" -L "https://api.clubhouse.io/api/v2/stories/$story_id?token=$token"`

story_name=`echo $story | jq -r '.name'`
if [ "$story_name" = 'null' ]; then
  echo "Could not extract name, exiting..."
  echo
  echo $story
  exit 2
fi

if [ "$toggl" = true ]; then
  epic_id=`echo $story | jq .epic_id`
  epic_name=`curl -s -X GET -H "Content-Type: application/json" -L "https://api.clubhouse.io/api/v2/epics/$epic_id?token=$token" | jq -r .name`

  toggl "$story_name ($story_id)" $epic_id $epic_name
  echo
fi

convert=`echo $story_name | sed 's/[^a-zA-Z]/-/g'`

existing_branch=`echo $story | jq -r '.branches[0].name'`

if [ "$existing_branch" = 'null' ]; then
  git checkout master && git pull && git checkout -b $user/ch$story_id/${convert,,} && git push -u

  if [ $? -eq 0 ]; then
    echo Moving story to \"In Progress\"
    curl --silent -X PUT -H "Content-Type: application/json" -d '{ "workflow_state_id": 500000019 }' -L "https://api.clubhouse.io/api/v2/stories/$story_id?token=$token" > /dev/null
    echo All done.
  else
    echo Something went wrong, not moving Clubhouse issue
  fi
else
  git fetch
  git checkout $existing_branch
fi
