#!/bin/bash

if [ -z "$1" ]; then
  echo "Missing company parameter (e.g. Lingio)"
  exit 1
fi

if [ -z "$2" ]; then
  BRANCH=`git rev-parse --abbrev-ref HEAD | sed 's/-/ /g' | sed 's/\//: /'`
else
  BRANCH="$2"
fi

SUBDOMAIN=`echo $BRANCH | sed 's/[^a-zA-Z0-9]/-/g' | cut -d - -f -2`
PRODUCT=$1
FOLDER="$PRODUCT.wappia.net/$SUBDOMAIN"
URL="https://$SUBDOMAIN.$PRODUCT.wappia.net"

echo --- Building...
export REACT_APP_VERSION="`git rev-list --all --count`"
npm run build
echo --- Uploading build
cd build && tar -cz . | ssh builds@wappia.net "rm -rf $FOLDER ; mkdir -p $FOLDER && cd $FOLDER && tar -xz"

echo --- deployed at $URL

echo $URL > /tmp/deploy-branch
