#!/bin/bash

SUBDOMAIN=`echo $2 | sed 's/[^a-zA-Z0-9]/-/g'`
PRODUCT=$1
FOLDER="$PRODUCT.wappia.net/$SUBDOMAIN"
URL="https://$SUBDOMAIN.$PRODUCT.wappia.net"

echo --- Building...
yarn build
echo --- Uploading build
cd build && tar -cz . | ssh builds@wappia.net "rm -rf $FOLDER ; mkdir $FOLDER && cd $FOLDER && tar -xz"

echo --- deployed at $URL

echo $URL > /tmp/deploy-branch
