#!/bin/bash

show_help() {
  echo "
  ========= MULTI ===============

  Awesome little tool that creates clones from a parent ticket, sets the correct epic and project as well as relationship to parent.
  It is so cute, you need to see: https://i.imgur.com/BHdgU8h.gif

    Usage:
    multi <STORY_ID> <DESCRIPTION>

    EXAMPLES:
    multi 1234
  "
  exit 0
}

story_id="$1"
description="$2"
user="$tools_clubhouse_user"
token="$tools_clubhouse_api_token"

if [ -z "$story_id" ]; then
  show_help
fi

if [ -z "$description" ]; then
  show_help
fi

re='^[0-9]+$'
if ! [[ $story_id =~ $re ]] ; then
   echo "error: Clubhouse ID not a number" >&2
   exit 1
fi

story=`curl --silent -X GET -H "Content-Type: application/json" -L "https://api.clubhouse.io/api/v2/stories/$story_id?token=$token"`

story_name=`echo $story | jq -r '.name'`
epic=`echo $story | jq -r '.epic_id'`
project=`echo $story | jq -r '.project_id'`

if [ "$story_name" = 'null' ]; then
  echo "Could not extract name, exiting..."
  echo
  echo $story
  exit 2
fi

for mf in game browse translate settings homeless onboarding auth; do
  name="$mf $story_name"
  echo $name
  curl --silent -X POST -H "Content-Type: application/json" -d "{ 
    \"description\": \"$description\",
    \"epic_id\": $epic,
    \"project_id\": $project,
    \"labels\": [{\"name\": \"web-${mf}\"}],
    \"name\": \"$name\",
    \"story_links\": [{\"object_id\": \"$story_id\", \"verb\": \"related to\"}],
    \"workflow_state_id\": \"500002055\"
  }" -L "https://api.clubhouse.io/api/v2/stories?token=$token"
done
