#!/bin/bash

. env.sh

echo Getting branch...
RAW=`git rev-parse --abbrev-ref HEAD`
BRANCH=`echo $RAW | sed 's/-/ /g' | sed 's/\//: /'`

echo Pushing...
git push -u 

deploy-branch "lingio" "$RAW"
URL=`cat /tmp/deploy-branch`

regex="ch([0-9]+)/"
if [[ $BRANCH =~ $regex ]]; then
  clubhouse_id="${BASH_REMATCH[1]}"
fi

echo Creating pull request...
hub pull-request -r "$REVIEWER" -F- <<<"$BRANCH 

[Deploy]($URL)

[Clubhouse](https://app.clubhouse.io/lingio/story/$clubhouse_id)"
