#!/bin/bash

echo Getting branch...
RAW=`git rev-parse --abbrev-ref HEAD`
BRANCH=`echo $RAW | sed 's/-/ /g' | sed 's/\//: /'`

exit 
echo Pushing...
git push -u 

deploy-branch "lingio" "$RAW"
URL=`cat /tmp/deploy-branch`

regex="ch([0-9]+)/"
if [[ $BRANCH =~ $regex ]]; then
  CLUBHOUSE_ID="${BASH_REMATCH[1]}"

  echo Moving Clubhouse story to Review
  . env.sh 
  curl -X PUT   -H "Content-Type: application/json"   -d '{ "workflow_state_id": 500000022 }' -L "https://api.clubhouse.io/api/v2/stories/1934?token=$CLUBHOUSE_API_TOKEN"
fi

echo Creating pull request...
hub pull-request -r Zanshe -F- <<<"$BRANCH 

Deploy: $URL"
