#!/bin/bash

token=$tools_toggl_api_token
project_id=$tools_toggl_project_id
description="$1"

if [ "$1" == "help" ] || [ "$1" == "" ]; then
cat << EOF
USAGE:
  toggl <description>

  description
    The description that will be displayed on the time entry

ENVIRONMENT VARIABLES:
  tools_toggl_api_token
    API token for Toggl

  tools_toggl_project_id
    Id for the project that time entries should be associated with
EOF
  exit 0
fi

curl -s -o /dev/null -u $token:api_token -X GET https://www.toggl.com/api/v8/me

if [ ! -z $project_id ]; then
  pid=",\"pid\":$project_id"
fi

result=`curl -s -u $token:api_token -H "Content-Type: application/json" -d "{\"time_entry\":{\"description\":\"$description\"$pid,\"created_with\":\"tools/toggl\"}}" -X POST https://www.toggl.com/api/v8/time_entries/start`

data=`echo $result | jq .`

if [ -z "$data" ]; then
  printf "\nFailed to start Toggl timer\nReason: $1\n"
else
  echo 'Successfully started Toggl timer'
fi
